eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8030
spring:
  application:
    name: cloudZuul
zuul:
  routes:
    ribbonClient:
      path: /ribbonClient/**
      serviceId: ribbonClient